ZayShop/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('zay/' , include("zayapp.urls")),
    path('crm/' , include("crm.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

crm/urls.py
from django.urls import path
from .views import *

app_name = 'crm'

urlpatterns = [
    path('' , HomeView.as_view() , name='home'),
    path('crm/' , CrmView.as_view() , name='contact'),
    path('user/' , UserListView.as_view() , name='user'),
    path('detail/<int:pk>/' , CrmDetailView.as_view(),name='crm-detail'),
    path('detail/<int:pk>/delete/' , DeleteCrmView.as_view() , name='delete'),
    path('orders/' , Ordersview.as_view() , name='order'),
    path('products/' , ProductsListView.as_view() , name='product'),
    path('create/' , ProductsCreateView.as_view() , name='create'),
    path('products/<int:pk>/' , ProductsDetailView.as_view() , name='product-details'),
]

zayapp/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'zay'
urlpatterns = [
    path('' , HomeView.as_view() , name='home'), # homePage view only for introducing the website
    path('shop/' , ProductView.as_view() , name='shop'), # All products in the database
    path('shop/<int:pk>/' , SingleProduct.as_view() , name='single'), # Single product view     
    path('cart/' , CartDetailView.as_view() , name='cart'), # Cart View 
    path('cart/<int:pk>/delete/' , CartItemDeleteView.as_view() , name='delete'), # Deleting products
    path('shop/men/' , MenView.as_view() , name='men'), # filtering the products to the men products only 
    path('shop/women/' , WomenView.as_view() , name='women'), # filtering the products to the women products only
    path('login/' , CustomerLoginView.as_view() , name='login'), # Login form view
    path('register/' , CustomerRegisterView.as_view() , name='register'), # registration form 
    path('logout/' , views.Logout , name='logout'), # logout url without view
    path('register/form' , UserProfileFormView.as_view() , name='form' ), # Form for taking more informations about the user 
    path('profile/' , UserProfileDetailView.as_view() , name='profile'), # profile view for the user 
    path('profile/update/' , UserProfileUpdateView.as_view() , name='update'), # Updating the profile view of the user if he wanted
    path('about/' , AboutView.as_view() , name='about'), # About view for the website 
    path('contact/' , ContactFormView.as_view() , name='contact'), # let the users to contact the admins or the owner of the site 
]

zayapp/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from datetime import timedelta
from django.contrib.auth.models import User , AbstractUser
# Create your models here.

class nations(models.Model):
    name = models.CharField(max_length=50 , default='')
    code = models.CharField(max_length=3 , default='')

    def __str__(self):
        return self.name



class City(models.Model):
    name = models.CharField(max_length=100 , default='')
    code = models.CharField(max_length=3 , default='')

    def __str__(self):
        return self.name


class Cart(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    total_items = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'Cart of {self.user.username} '

    def update_total_items(self):
        print("Updating total items...")  # Debugging print
        self.total_items = sum(item.quantity for item in self.items.all())
        print(f"New total items: {self.total_items}")  # Debugging print
        self.save()

    def total_price(self):
        return sum(item.total_price for item in self.items.all())


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Season(models.Model):
    season = models.CharField(max_length=200)

    def __str__(self):
        return self.season
    

class Products(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category , on_delete=models.CASCADE)
    season = models.ForeignKey(Season , on_delete=models.CASCADE)
    image = models.FileField(upload_to='static/image/' , blank=True , null=True)
    added_by = models.ForeignKey(User , on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    def __str__(self):
        return self.name

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items'  , default='')
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    size = models.CharField(max_length=10 , null=True , default='')

    def __str__(self):
        return f'{self.quantity} x {self.product.name}'
    
    @property
    def total_price(self):
        return self.quantity * self.product.price
    
class Contact(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_DEFAULT , null=True , default='')
    subject = models.CharField(max_length=155 , default='')
    message = models.TextField(default='message')
    phone = models.CharField(max_length=12 , default='')
    email = models.EmailField(default='')
    Custom_id = models.PositiveIntegerField(unique=True , null=True , blank=True)
    def save(self,*args , **kwargs):
        if self.Custom_id is None:
            last_customer = Contact.objects.all().order_by('Custom_id').last()
            if last_customer :
                self.Custom_id = last_customer.Custom_id + 1
            else:
                self.Custom_id = 1
        super().save(*args , **kwargs)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.CharField(max_length=20 , default='')
    city = models.ForeignKey(City, on_delete=models.CASCADE , default='')
    phone = models.CharField(max_length=15 , default='')
    address = models.CharField(max_length=100 , default='')
    image = models.FileField(upload_to='static/image', blank=True)
    cart = models.ForeignKey(Cart , on_delete=models.SET_NULL , default='' , null=True)    
    nationality = models.ForeignKey(nations , on_delete=models.SET_DEFAULT , default=51)

    def __str__(self):
        return self.user.username

class Order(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    size = models.CharField(max_length=5)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Order {self.id} by {self.user.email}"

    @property
    def total_price(self):
        return self.quantity * self.product.price
    

zayapp/forms.py
# accounts/forms.py
from django import forms
from .models import UserProfile , Contact


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['email' , 'phone' , 'city' , 'address' , 'image' , 'nationality']


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['subject' , 'message' , 'phone' , 'email']

zayapp/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.generic import View
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect 
from django.urls import reverse, reverse_lazy
from django.contrib.auth.views import LoginView , LogoutView 
from django.contrib.auth.models import User
from django.contrib.auth import login  , logout , authenticate
from django.views.generic import ListView , DetailView , DeleteView , UpdateView , CreateView , FormView
from .models import Products , Category , Season , CartItem , Cart , City , UserProfile , Order
from django.contrib.auth.forms import UserCreationForm
from .forms import UserProfileForm , ContactForm
from django.contrib import messages
# Create your views here.

class HomeView(ListView):
    queryset = Products.objects.all()
    template_name = 'pages/home.html'
    context_object_name = 'product'

class AboutView(ListView):
    queryset = Products.objects.all()
    template_name = 'pages/about.html'

class ProductView(ListView):
    queryset = Products.objects.all()
    template_name = 'pages/products.html'
    context_object_name = 'products'
    paginate_by = 6
    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Products.objects.filter(
                Q(name__icontains=query) |
                Q(description__icontains=query) |
                Q(price__icontains=query) 
            )
        return Products.objects.all()

    def get(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        if not queryset.exists() and request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return JsonResponse({'message': 'Product not found'}, status=404)
        paginator = Paginator(queryset, self.paginate_by)
        page = request.GET.get('page')
        products = paginator.get_page(page)
        return render(request, self.template_name, {'products': products})

class SingleProduct(DetailView):
    queryset = Products.objects.all()
    context_object_name = 'product'
    template_name = 'pages/single-product.html'
    
    def post(self, request, *args, **kwargs):
        if request.POST.get('submit') == 'addtocart':
            if not request.user.is_authenticated:
                messages.error(request, "You need to be logged in to perform this action.")
                return redirect(reverse("zay:login") + "?message=You need to be logged in to perform this action.")

            product = get_object_or_404(Products, pk=kwargs['pk'])
            cart, created = Cart.objects.get_or_create(user=request.user)

            size = request.POST.get('product-size')
            quantity = int(request.POST.get('product-quantity', 1))

            cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product, size=size)
            if not created:
                cart_item.quantity += quantity
            else:
                cart_item.quantity = quantity
            cart_item.save()

            # Update the total items in the cart
            cart.update_total_items()
            
            messages.success(request, f"{product} is added successfully with quantity {quantity} ")
            return redirect(reverse("zay:cart") + f"?message={product} is added successfully with quantity {quantity} ")
        elif request.POST.get('submit') == 'buy':
            product = get_object_or_404(Products, pk=kwargs['pk'])
            size = request.POST.get('product-size')
            quantity = int(request.POST.get('product-quantity', 1))
            user_profile = UserProfile.objects.filter(user=request.user).first()
            
            if not user_profile or not user_profile.city or not user_profile.phone or not user_profile.address or not user_profile.nationality:
                messages.error(request, "Please complete your profile information before purchasing.")
                return redirect('zay:form')
            order, created = Order.objects.get_or_create(user=user_profile, product=product, size=size, quantity=quantity)
            order.save()
        return super().get(request, *args, **kwargs)
class CartDetailView(DetailView):
    model = Cart
    template_name = 'pages/cart_detail.html'  # #new
    context_object_name = 'cart'  # #new

    def get_object(self, queryset=None):
        return get_object_or_404(Cart, user=self.request.user)        


class CartItemDeleteView(DeleteView):
    model = CartItem
    template_name = 'pages/cart_delete.html'

    def get_success_url(self):
        return reverse_lazy('zay:cart')
    
class MenView(ListView):
    queryset = Products.objects.all().filter(category=2)
    template_name = 'pages/men.html'
    context_object_name = 'men'


class WomenView(ListView):
    queryset = Products.objects.all().filter(category=3)
    template_name = 'pages/women.html'
    context_object_name = 'women'
    
    
class CustomerLoginView(LoginView):
    template_name = 'pages/login.html'
    fields = "__all__"
    success_url = reverse_lazy('zay:home')

    def get_success_url(self):
        return reverse_lazy('zay:home')
    def form_valid(self, form):
        print("Form is valid")
        return super().form_valid(form)

    def form_invalid(self, form):
        print("Form is invalid")
        return super().form_invalid(form)


class CustomerRegisterView(FormView):
    template_name = 'pages/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy("zay:form")
    
    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request,user)
        return super(CustomerRegisterView , self).form_valid(form)
    def get(self,*args,**kwargs ):
        if self.request.user.is_authenticated :
            return redirect('zay:login')
        return super(CustomerRegisterView , self ).get(*args,**kwargs)
    def form_invalid(self,form):
        print("Form is invalid")
        print(form.errors)
        return super().form_invalid(form)

class UserProfileFormView(FormView):
    template_name = 'pages/form.html'
    form_class = UserProfileForm
    success_url = reverse_lazy('zay:home')

    def form_valid(self, form):
        user_profile = form.save(commit=False)
        user_profile.user = self.request.user
        user_profile.save()
        return super().form_valid(form)
    

class ContactFormView(FormView):
    template_name = 'pages/contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('zay:home')

    def form_valid(self , form):
        contact = form.save(commit=False)
        contact.user = self.request.user
        contact.save()
        return super().form_valid(form)
    
class UserProfileDetailView(LoginRequiredMixin, DetailView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = 'pages/profile.html'
    context_object_name = 'profile'

    def get_object(self):
        return UserProfile.objects.get(user=self.request.user)
    
    def get(self , request , *args , **kwargs):
        user_profile = UserProfile.objects.filter(user=request.user).first()
        
        if not user_profile or not user_profile.city or not user_profile.phone or not user_profile.address or not user_profile.nationality:
            messages.error(request, "Please complete your profile information before purchasing.")
            return redirect(reverse("zay:form") + "?message=Please complete your profile information first.")

        if not request.user.is_authenticated:
            messages.info(request , "You need to be registered and logged in to view your profile")
            return redirect('zay:login')
        
        return super().get(request, *args, **kwargs)

class UserProfileUpdateView(LoginRequiredMixin , UpdateView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = 'pages/profile_update.html'
    context_object_name = 'profile'
    success_url = reverse_lazy('zay:profile')

    def get_object(self):
        return UserProfile.objects.get(user=self.request.user)


def Logout(request):
    logout(request)
    return redirect('zay:login')

zayapp/templates/pages/buy.html
{% extends 'pages/base.html' %}


{% block content %}
    {% if orders %}
    <h1> {{orders.user.username}} </h1>
    <h1> {{orders.address}} </h1>
    <h1> {{orders.phone}} </h1>
    <h1> {{orders.city}} </h1>
    <h1> {{orders.nationality}} </h1>
    <h1> {{orders.product}} </h1>
    {% else %}
    <h1> No orders yet </h1>
    {% endif %}
{% endblock content %}

zayapp/templates/pages/cart_detail.html
<!-- templates/cart_detail.html -->
{% extends 'pages/base.html' %}
 {% block content %}
 <style>
    body{
        background-color: #f5f5f5;
    }
    .cart
    {
        background-color: #fff;
    }
    .img{
        width: 90%;
        padding: 0%;
    }
 </style>
 <center>     
    <h1>Your Cart</h1>
    <h5>Total Items: {{cart.total_items}}</h5>
    <h6> <b>Total Price:  ${{cart.total_price}} </b> </h6>
 </center>
 <br>   
    {% if cart.items.all %}
    {% for item in cart.items.all  %}
    <div class="container cart">
        <div class="row">
            <div class="col-3">
                <img src="{{item.product.image.url}}" class="img img-fluid">
            </div>
            <div class="col-3">
                <h3 style="font-size: 40px;" class="mt-3">{{ item.product.name }}</h3>
                <p>Size: {{ item.size }}</p>
                <p>Quantity: {{ item.quantity }}</p>
                <i> Price : ${{item.product.price}} </i>
                <br><br>
                <i><b>Total price : $ {{item.total_price}} </b></i>
                <br>
                <br>
                <a href="{% url 'zay:delete' item.id %}" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
    <hr>
    {% endfor %}
    {% else %}
    <div class="container p-5 mb-5 card">
        <div class="row">
            <div class="col-12">
                
                <h1 class="text-center">Your Cart is Empty</h1>
            </div>
            <div class="col-12 text-center">
                <a href="{% url 'zay:shop' %}" class="btn btn-success p-3">Shop Now</a>
            </div>
        </div>
    </div>
    {% endif %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        function showMessage(message) {
            Swal.fire({
                title: 'Added',
                text: message,
                icon: 'success',
                confirmButtonText: 'OK'
            });
        }
        // Ensure the DOM is fully loaded before running the script
        document.addEventListener("DOMContentLoaded", function() {
          // Check if there's a message parameter in the URL
          const urlParams = new URLSearchParams(window.location.search);
          const message = urlParams.get('message');
          if (message) {
              showMessage(message);
              console.log("Added")
          } 
        });
    </script>
 {% endblock content %}

zayapp/templates/pages/products.html
{% extends 'pages/base.html' %}

{% load static %}


{% block content %}
    <title> Zay | Shop </title>
<style>
{% comment %} .product-overlay ul {
    opacity: 0;
    transition: opacity 0.3s ease-in-out;
}
.product-overlay:hover ul {
    opacity: 1;
} {% endcomment %}
.product-wap {
    max-height: fit-content;
    max-width: fit-content; /* Adjust the width as needed */
}
.product-wap img {
    width: max-content;
    height: fit-content; /* Adjust the height as needed */
    object-fit:fill; /* Ensures the image covers the area without distortion */
    padding: 0;
}
.pagination .page-item .page-link{
    color: #000;
}


.pagination .page-item.active .page-link {
    background-color: #28a745;  /* Bootstrap's 'success' color */
    border-color: #28a745;  /* Bootstrap's 'success' color */
    color: white;
}

</style>    

    <!-- Start Content -->
    <div class=" container-fluid py-5">
        <div class="row">
            <div class="col-lg-3 px-5">
                <h1 class="h2 pb-4">Categories</h1>
                <ul class="list-unstyled templatemo-accordion">
                    <li class="pb-3">
                        <a class="collapsed d-flex justify-content-between h3 text-decoration-none text-dark" href="#">
                            Gender
                        </a>
                        <ul class="list-unstyled pl-3">
                            <li><a class="text-decoration-none text-dark" href="{% url 'zay:shop' %}">All Products</a></li>
                            <li><a class="text-decoration-none text-dark" href="{% url 'zay:men' %}">Men</a></li>
                            <li><a class="text-decoration-none text-dark" href="{% url 'zay:women' %}">Women</a></li>
                        </ul>
                    </li>
                    <li class="pb-3">
                        <a class="collapsed d-flex justify-content-between h3 text-decoration-none text-dark" href="#">
                            Sale
                        </a>
                        <ul id="collapseTwo" class=" list-unstyled pl-3">
                            <li><a class="text-decoration-none text-dark" href="#">Sport</a></li>
                            <li><a class="text-decoration-none text-dark" href="#">Luxury</a></li>
                        </ul>
                    </li>
                    <li class="pb-3">
                        <a class="d-flex justify-content-between h3 text-decoration-none text-dark" href="#">
                            Product
                        </a>
                        <ul id="collapseThree" class="list-unstyled pl-3">
                            <li><a class="text-decoration-none text-dark" href="#">Bag</a></li>
                            <li><a class="text-decoration-none text-dark" href="#">Sweather</a></li>
                            <li><a class="text-decoration-none text-dark" href="#">Sunglass</a></li>
                        </ul>
                    </li>
                </ul>
            </div>

            <div class="col-lg-9">
                <div class="row">
                    <div class="col-md-6">
                        <ul class="list-inline shop-top-menu pb-3 pt-1">
                            <li class="list-inline-item">
                                <a class="h3 text-dark text-decoration-none mr-3" href="{% url 'zay:shop' %}">All</a>
                            </li>
                            <li class="list-inline-item">
                                <a class="h3 text-dark text-decoration-none mr-3" href="{% url 'zay:men' %}">Men's</a>
                            </li>
                            <li class="list-inline-item">
                                <a class="h3 text-dark text-decoration-none" href="{% url 'zay:women' %}">Women's</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-6 pb-4">
                        <div class="d-flex">
                            <form action="{% url 'zay:shop' %}" method="get" class="modal-content modal-body border-0 p-0">
                                <div class="input-group mb-2">
                                    <input type="text" class="form-control" id="inputModalSearch" name="q" placeholder="Search ...">
                                    <button type="submit" class="input-group-text bg-success text-light">
                                        <i class="fa fa-fw fa-search text-white"></i>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="row">
                    {% if products %}
                    {% for product in products %}
                    <div class="col-md-4">
                        <div class="card mb-4 p-0 product-wap">
                            <div class="card">
                                <a href="{% url 'zay:single' product.id %}">               
                                    <img class="card-img rounded-0 img-fluid" src="{{product.image.url}}">
                            </a>
                        </div>
                        <div class="card-body">
                            <a href="{% url 'zay:single' product.id %}" class="h3 text-decoration-none text-dark"> {{product.name}} </a>
                                <ul class="w-100 list-unstyled d-flex justify-content-between mb-0">
                                    <li>M/L/X/XL</li>
                                    <li class="pt-2">
                                        <span class="product-color-dot color-dot-red float-left rounded-circle ml-1"></span>
                                        <span class="product-color-dot color-dot-blue float-left rounded-circle ml-1"></span>
                                        <span class="product-color-dot color-dot-black float-left rounded-circle ml-1"></span>
                                        <span class="product-color-dot color-dot-light float-left rounded-circle ml-1"></span>
                                        <span class="product-color-dot color-dot-green float-left rounded-circle ml-1"></span>
                                    </li>
                                </ul>
                                <ul class="list-unstyled d-flex justify-content-center mb-1">
                                    <li>
                                        <i class="text-warning fa fa-star"></i>
                                        <i class="text-warning fa fa-star"></i>
                                        <i class="text-warning fa fa-star"></i>
                                        <i class="text-muted fa fa-star"></i>
                                        <i class="text-muted fa fa-star"></i>
                                    </li>
                                </ul>
                                <p class="text-center mb-0"> ${{product.price}} </p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    
                    {% else %}

                    {% endif %}        
                </div>
            </div>
            {% if products.has_other_pages %}
                <nav aria-label="Page navigation" class=" d-flex justify-content-center text-center">
                    <ul class="pagination">
                        {% if products.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ products.previous_page_number }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <span class="page-link" aria-hidden="true">&laquo;</span>
                            </li>
                        {% endif %}
                        
                        {% for page_num in products.paginator.page_range %}
                            {% if products.number == page_num %}
                                <li class="page-item active"><span class="page-link">{{ page_num }}</span></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                            {% endif %}
                        {% endfor %}
                        
                        {% if products.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ products.next_page_number }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <span class="page-link" aria-hidden="true">&raquo;</span>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}

            <!-- End Content -->
        <section class="bg-light py-5">
        <div class="container my-4">
            <div class="row text-center py-3">
                <div class="col-lg-6 m-auto">
                    <h1 class="h1">Our Brands</h1>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        Lorem ipsum dolor sit amet.
                    </p>
                </div>
                <div class="col-lg-9 m-auto tempaltemo-carousel">
                    <div class="row d-flex flex-row">
                        <!--Carousel Wrapper--> 
                        <div class="col">
                            <div class="carousel slide carousel-multi-item pt-2 pt-md-0" id="multi-item-example" data-bs-ride="carousel">
                                <!--Slides-->
                                <div class="carousel-inner product-links-wap" role="listbox">

                                    <!--First slide-->
                                    <div class="carousel-item active">
                                        <div class="row">
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="{% static 'images/brand_01.png' %}" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src=" {% static 'images/brand_02.png' %}" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src=" {% static 'images/brand_03.png' %}" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src=" {% static 'images/brand_04.png' %}" alt="Brand Logo"></a>
                                            </div>
                                        </div>
                                    </div>
                                    <!--End First slide-->

                                </div>
                                <!--End Slides-->
                            </div>
                        </div>
                        <!--End Carousel Wrapper-->
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    <!--End Brands-->

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        document.querySelector('form[action="{% url 'zay:shop' %}"]').addEventListener('submit', function(event) {
        event.preventDefault();
        const form = event.target;
        fetch(form.action + '?' + new URLSearchParams(new FormData(form)), {
            headers: {
                'x-requested-with': 'XMLHttpRequest'
            }
        }).then(response => {
            if (response.status === 404) {
                Swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: 'Product not found',
                });
            } else {
                window.location.href = form.action + '?' + new URLSearchParams(new FormData(form));
            }
        });
    });
    </script>
{% endblock content %}