ZayShop/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('zay/' , include("zayapp.urls")),
    path('crm/' , include("crm.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

crm/urls.py
from django.urls import path
from .views import *

app_name = 'crm'

urlpatterns = [
    path('' , HomeView.as_view() , name='home'),
    path('crm/' , CrmView.as_view() , name='contact'),
    path('user/' , UserListView.as_view() , name='user'),
    path('detail/<int:pk>/' , CrmDetailView.as_view(),name='crm-detail'),
    path('detail/<int:pk>/delete/' , DeleteCrmView.as_view() , name='delete'),
    path('orders/' , Ordersview.as_view() , name='order'),
    path('products/' , ProductsListView.as_view() , name='product'),
    path('create/' , ProductsCreateView.as_view() , name='create'),
    path('products/<int:pk>/' , ProductsDetailView.as_view() , name='product-details'),
]

crm/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.

class UserModel(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    CustomId = models.PositiveBigIntegerField(unique=True , null=True , blank=True)

    def save(self,*args , **kwargs):
        if self.CustomId is None:
            last_customer = UserModel.objects.all().order_by('CustomId').last()
            if last_customer :
                self.Custom_id = last_customer.CustomId + 1
            else:
                self.CustomId = 1
        super().save(*args , **kwargs)

crm/forms.py
from django import forms
from zayapp.models import Products


class ProductsForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = ['name' , 'description' , 'price' , 'category' , 'season' ,  'quantity' , 'image']

crm/views.py
from django.shortcuts import render ,redirect
from django.db.models import Q
from django.http import JsonResponse
from zayapp.models import Contact , Order , UserProfile , Products
from django.views.generic import ListView , UpdateView , DeleteView , DetailView , CreateView , FormView , View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from .forms import ProductsForm
# Create your views here.

class HomeView(ListView):
    queryset = Products.objects.all()
    template_name = "pages/crmhome.html"


class CrmView(LoginRequiredMixin,ListView):
    template_name = "pages/crm.html"
    context_object_name = 'customers'
    login_url = reverse_lazy('crm:login')

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            query = query.strip().lower()  # Remove any leading/trailing whitespace and convert to lowercase
            print(f"Search Query: {query}")  # Debug print
            results = UserProfile.objects.filter(
                Q(user__username__icontains=query) |
                Q(email__icontains=query) |
                Q(phone__icontains=query)
            )
            print(f"Results Count: {results.count()}")  # Debug print
            return results
        return Contact.objects.all()
class CrmDetailView(LoginRequiredMixin , DetailView):
    queryset = Contact.objects.all()
    template_name = "pages/detail.html"
    context_object_name = "customersDetails"
    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

class DeleteCrmView(LoginRequiredMixin , DeleteView):
    model = Contact
    template_name = 'pages/delete.html'
    success_url = reverse_lazy('crm:contact')
    context_object_name = 'contacts'


class Ordersview(LoginRequiredMixin , ListView):
    template_name = "pages/ordersAdmin.html"
    context_object_name = 'orders'
    login_url = reverse_lazy('crm:login')

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            query = query.strip().lower()  # Remove any leading/trailing whitespace and convert to lowercase
            print(f"Search Query: {query}")  # Debug print
            results = Order.objects.filter(
                Q(user__user__username__icontains=query) |
                Q(product__name__icontains=query)|
                Q(product__price__icontains=query)
            )
            print(f"Results Count: {results.count()}")  # Debug print
            return results
        return Order.objects.all()
        
class UserListView(LoginRequiredMixin , ListView):
    template_name = "pages/userModel.html"
    context_object_name = 'users'
    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            query = query.strip().lower()  # Remove any leading/trailing whitespace and convert to lowercase
            print(f"Search Query: {query}")  # Debug print
            results = UserProfile.objects.filter(
                Q(user__username__icontains=query) |
                Q(email__icontains=query) |
                Q(phone__icontains=query) |
                Q(city__name__icontains=query)|
                Q(nationality__name__icontains=query)|
                Q(address__icontains=query)
            )
            print(f"Results Count: {results.count()}")  # Debug print
            return results
        return UserProfile.objects.all()
class ProductsListView(LoginRequiredMixin , ListView):
    template_name = "pages/productsAdmin.html"
    context_object_name = 'products'
    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            query = query.strip().lower()  # Remove any leading/trailing whitespace and convert to lowercase
            print(f"Search Query: {query}")  # Debug print
            results = Products.objects.filter(
                Q(name__icontains=query) |
                Q(description__icontains=query) |
                Q(price__icontains=query) |
                Q(category__name__iexact=query)
            )
            print(f"Results Count: {results.count()}")  # Debug print
            return results
        return Products.objects.all()
class ProductsCreateView(LoginRequiredMixin , FormView):
    template_name = "pages/create.html"
    form_class = ProductsForm
    success_url = reverse_lazy('crm:products')
    
    def form_valid(self , form):
        product = form.save(commit=False)
        product.added_by = self.request.user
        product.save()
        return super().form_valid(form)
    

class ProductsDetailView(LoginRequiredMixin , DetailView):
    queryset = Products.objects.all()
    template_name = 'pages/products-detail.html'
    context_object_name = 'product'

crm/templates/pages/create.html
{% extends 'pages/crmbase.html' %}

{% block content %}
  <title> Zay | Contact </title>
    <!-- Start Contact -->
    <style>
    .login-box {   
        width: 100%;
        padding: 40px;
        margin-top:430px;
        margin-bottom: -330px;
        margin-right: -670px;
        transform: translate(-50%, -55%);
        background: transparent;
        box-sizing: border-box;
        box-shadow: 0 15px 25px rgba(0,0,0,.6);
        border-radius: 10px;
    }
    
    .login-box p:first-child {
      margin: 0 0 30px;
      padding: 0;
      color: black;
      text-align: center;
      font-size: 1.5rem;
      font-weight: bold;
      letter-spacing: 1px;
    }
    
    .login-box .user-box {
      position: relative;
    }
    
    .login-box .user-box input {
      width: 100%;
      padding: 10px 0;
      font-size: 16px;
      color: white;
      margin-bottom: 30px;
      border: none;
      border-bottom: 1px solid #fff;
      outline: none;
      background: transparent;
    }
    
    .login-box .user-box label {
      position: absolute;
      top: 0;
      left: 0;
      padding: 10px 0;
      font-size: 16px;
      color: white;
      pointer-events: none;
      transition: .5s;
    }
    
    .login-box .user-box input:focus ~ label,
    .login-box .user-box input:valid ~ label {
      top: -20px;
      left: 0;
      color: white;
      font-size: 12px;
    }
    
    .login-box form a {
      position: relative;
      display: inline-block;
      padding: 10px 20px;
      font-weight: bold;
      color: white;
      font-size: 16px;
      text-decoration: none;
      text-transform: uppercase;
      overflow: hidden;
      transition: .5s;
      margin-top: 40px;
      letter-spacing: 3px
    }
    
    .login-box a:hover {
      background: #fff;
      color: white;
      border-radius: 5px;
    }
    
    .login-box a span {
      position: absolute;
      display: block;
    }
    
    .login-box a span:nth-child(1) {
      top: 0;
      left: -100%;
      width: 100%;
      height: 2px;
      background: linear-gradient(90deg, transparent, #fff);
      animation: btn-anim1 1.5s linear infinite;
    }
    
    @keyframes btn-anim1 {
      0% {
        left: -100%;
      }
    
      50%,100% {
        left: 100%;
      }
    }
    
    .login-box a span:nth-child(2) {
      top: -100%;
      right: 0;
      width: 2px;
      height: 100%;
      background: linear-gradient(180deg, transparent, #fff);
      animation: btn-anim2 1.5s linear infinite;
      animation-delay: .375s
    }
    
    @keyframes btn-anim2 {
      0% {
        top: -100%;
      }
    
      50%,100% {
        top: 100%;
      }
    }
    
    .login-box a span:nth-child(3) {
      bottom: 0;
      right: -100%;
      width: 100%;
      height: 2px;
      background: linear-gradient(270deg, transparent, #fff);
      animation: btn-anim3 1.5s linear infinite;
      animation-delay: .75s
    }
    
    @keyframes btn-anim3 {
      0% {
        right: -100%;
      }
    
      50%,100% {
        right: 100%;
      }
    }
    
    .login-box a span:nth-child(4) {
      bottom: -100%;
      left: 0;
      width: 2px;
      height: 100%;
      background: linear-gradient(360deg, transparent, #fff);
      animation: btn-anim4 1.5s linear infinite;
      animation-delay: 1.125s
    }
    
    @keyframes btn-anim4 {
      0% {
        bottom: -100%;
      }
    
      50%,100% {
        bottom: 100%;
      }
    }
    
    .login-box p:last-child {
      color: black;
      font-size: 14px;
    }
    
    .login-box a.a2 {
      color: black;
      text-decoration: none;
    }
    
    .login-box a.a2:hover {
      background: transparent;
      color: black;
      border-radius: 5px;
    }
    #login{
        font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
    }
    #submit{
        background-color:;
    }
    </style>
    <center>
        <div class="container mt-5 mb-5" >
            <div class="row justify-content-center">
            <div class="col-6 mt-5">
                <div class="login-box bg-dark">
                  {% if messages %}
                    <div class="alert alert-info" role="alert">
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    </div>
                  {% endif %}
                    <p class="text-light" id="login">Adding Product</p>
                    <form action="{% url 'crm:create' %}" method="post">
                        {% csrf_token %}
                        <div class="user-box">
                            {{form.name}}
                            <label class="text-light">Product Name</label>
                        </div>
                        <div class="user-box">
                            {{form.price}}
                            <label class="text-light">Product Price</label>
                        </div>
                        <div class="user-box">
                            {{form.quantity}}
                            <label class="text-light">Product Quantity in stock</label>
                        </div>
                        <div class="user-box mt-3 ">
                            {{form.description}}
                        </div>
                        
                        <div class="user-box mb-3">
                            {{form.category}}
                            <label class="text-light">Category</label>
                        </div>                    
                        <div class="user-box mb-3">
                            {{form.image}}
                            <label class="text-light">Image</label>
                        </div>
                        <input type="submit" value="Add Product" class="btn btn-light px-5 mt-2" id='submit'>
                    </form>
                </div>            
            </div>
        </div>
    </div>
    </center>
    <!-- End Contact -->
{% endblock content %}

crm/templates/pages/crm.html
{% extends 'pages/crmbase.html' %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Customer List</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            padding: 8px 12px;
            border: 1px solid #ccc;
        }
        th {
            background-color: #f4f4f4;
        }
        footer{
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
        }
    </style>
</head>
<body>
    <h1>Customer List</h1>
    {% if customers %}
    <table class="table table-striped table-hover">
        <thead class="text-light bg-dark">
            <tr>
                <th>ID</th>
                <th>Username</th>
                <th>Email</th>
                <th>Phone</th>
                <th>subject</th>
            </tr>
        </thead>
        <tbody>
            {% for customer in customers %}
            <tr>
                <td><a href="{% url 'crm:detail' customer.id %}" style="text-decoration: none; color: black;"> {{ customer.Custom_id }}</a></td>
                <td>{{ customer.user.username }}</td>
                <td> {{customer.email}} </td>
                <td> {{customer.phone}} </td>
                <td> {{customer.subject}} </td>
            </tr>
            {% endfor %}
            {% else %}
            <h1> No complaints </h1>
            {% endif %}
        </tbody>
    </table>
</body>
</html>

{% endblock content %}

crm/templates/pages/crmbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" 
    integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" 
    crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">
</head>
<body>
        <!-- Start Top Nav -->
        <nav class="navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block" id="templatemo_nav_top">
            <div class="container text-light">
                <div class="w-100 d-flex justify-content-between">
                    <div>
                        <i class="fa fa-envelope mx-2"></i>
                        <a class="navbar-sm-brand text-light text-decoration-none" href="mailto:info@company.com">info@company.com</a>
                        <i class="fa fa-phone mx-2"></i>
                        <a class="navbar-sm-brand text-light text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
                    </div>
                    <div>
                        <a class="text-light" href="https://fb.com/templatemo" target="_blank" rel="sponsored"><i class="fab fa-facebook-f fa-sm fa-fw me-2"></i></a>
                        <a class="text-light" href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram fa-sm fa-fw me-2"></i></a>
                        <a class="text-light" href="https://twitter.com/" target="_blank"><i class="fab fa-twitter fa-sm fa-fw me-2"></i></a>
                        <a class="text-light" href="https://www.linkedin.com/" target="_blank"><i class="fab fa-linkedin fa-sm fa-fw"></i></a>
                    </div>
                </div>
            </div>
        </nav>
        <!-- Close Top Nav -->
    
    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light shadow">
        <div class="container d-flex justify-content-between align-items-center">

            <p class="navbar-brand text-success logo h1 align-self-center">
                <a href="{% url 'crm:home' %}" class="text-decoration-none text-success" style="font-family:'Times New Roman', Times, serif; font-size: 2rem;">
                    Zay Administration
                </a>
            </p>

            <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
                <div class="navbar align-self-center justify-content-between d-flex">
                    <a href="{% url 'crm:product' %}" class="btn btn-dark mx-2">Products</a>
                    <a href="{% url 'crm:order' %}" class="btn btn-dark mx-2">Orders</a>
                    <a href="{% url 'crm:contact' %}" class="btn btn-dark mx-2">Contact</a>
                    <a href="{% url 'crm:user' %}" class="btn btn-dark mx-2">User</a>
                    <a href="{% url 'crm:create' %}" class="btn btn-dark mx-2">Create new product</a>
                </div>
            </div>

        </div>
    </nav>
    <!--Content--> 
    {% block content %}
    {% endblock content %}

    <!--/content-->
    <script>
        window.addEventListener('load', function() {
            const url = new URL(window.location.href);
            if (url.searchParams.has('q')) {
                url.searchParams.delete('q');
                window.history.replaceState({}, document.title, url.toString());
            }
        });
    </script>
</body>
</html>

crm/templates/pages/crmhome.html
{% extends 'pages/crmbase.html' %}


{% block content %}
<style>
    h1{
        font-size: 6.5rem;
        font-family: 'Times New Roman', Times, serif;
    }
</style>
<div class="container-fluid vh-100 d-flex justify-content-center align-items-center">
    <div class="text-center">
        <h1 class="text text-success">
            Zay Administration
        </h1>
        <a href="{% url 'crm:product' %}" class="btn btn-dark">Products</a>
        <a href="{% url 'crm:order' %}" class="btn btn-dark">Orders</a>
        <a href="{% url 'crm:contact' %}" class="btn btn-dark">Contact</a>
        <a href="{% url 'crm:user' %}" class="btn btn-dark">User</a>
        <a href="{% url 'crm:create' %}" class="btn btn-dark">Create new product</a>
    </div>
</div>

{% endblock content %}

crm/templates/pages/delete.html
{% extends 'pages/crmbase.html' %}

{% block content %}
    <h1> Confirm Deletion </h1>

    <p>Are you sure you want to delete {{contacts.user.username}} record? </p>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Confirm" class="btn btn-danger" id="">
        <a href="{% url 'crm:detail' contacts.id %}" class="btn btn-dark"> Cancel </a>
    </form>
{% endblock content %}

crm/templates/pages/detail.html
{% extends 'pages/crmbase.html' %}


{% block content %}
<h1 class="mx-4">Customer Detail</h1>
<div class="card m-5" style="width: fit-content;">
    <div class="card-header">
      {{customersDetails.user.username}}
    </div>
    <div class="card-body">
      
      <p class="card-text">
        <strong style="display: none;" id="id"> {{customersDetails.id}}</strong>
        <strong>Username : </strong>{{customersDetails.user.username}}  <br>  
        <strong> Email : </strong> {{customersDetails.email}} <br>
        <strong> Phone : </strong> {{customersDetails.phone}} <br>
        <strong> Adress : </strong> {{customersDetails.subject}} <br>
        <strong> message :  </strong> {{customersDetails.message}} <br>
      </p>
      <a href="#" class="btn btn-dark">update</a>
        {% comment %} <div>
            <button onclick="confirmDelete({{ customersDetails.id }})" class="btn btn-danger">Done</button>
        </div> {% endcomment %}

      <a href="{% url 'crm:delete' customersDetails.id %}" class="btn btn-danger"> Delete</a>
    {% comment %} <form id="delete-form" action="{% url 'crm:delete' %}" method="post" style="display:none;">
        {% csrf_token %}
    </form> {% endcomment %}
{% comment %} 
    <script>
    function confirmDelete(contactId) {
      contactId = document.getElementById('id').value;
        if (confirm("Are you sure that you done with this contact?")) {
            var form = document.getElementById('delete-form');
            form.action = '/crm/detail/' + contactId + '/delete/';
            form.submit();
        }
    }
    </script> {% endcomment %}
    </div>
  </div>
  <a href="{% url 'crm:contact'%}" class="btn btn-dark mx-4"> <- Contacts </a>

{% endblock content %}

crm/templates/pages/ordersAdmin.html
{% extends 'pages/crmbase.html' %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>order List</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            padding: 8px 12px;
            border: 1px solid #ccc;
        }
        th {
            background-color: #f4f4f4;
        }
        footer{
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
        }
    </style>
</head>
<body>
    <h1 class="text-center text-dark mb-2" style="font-family:'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif; font-style: italic;">Orders List</h1>
    <div class="px-5">
        <form action="{% url 'crm:order' %}" method="get" class="modal-content modal-body border-0 px-5 ">
            <div class="input-group mb-2">
                <input type="text" class="form-control" id="inputModalSearch" name="q" placeholder="Search [name , price , id , category ,all(to get all of them)] ...">
                <button type="submit" class="input-group-text bg-success text-light">
                    <i class="fa fa-fw fa-search text-white"></i>
                </button>
            </div>
        </form>
    </div>
    {% if orders %}
    <table class="table table-striped table-hover">
        <thead class="text-light bg-dark">
            <tr>
                <th>ID</th>
                <th>Username</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Product</th>
                <th> address </th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
            <tr>
                <td> {{order.id}} </td>
                <td>{{ order.user }}</td>
                <td> {{order.user.email}} </td>
                <td> {{order.user.phone}} </td>
                <td> {{order.product}} </td>
                <td> {{order.user.address}} </td>
            </tr>
            {% endfor %}
            {% else %}
            <h1> No Orders </h1>
            {% endif %}
        </tbody>
    </table>
</body>
</html>

{% endblock content %}

crm/templates/pages/productsAdmin.html
{% extends 'pages/crmbase.html' %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>product List</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            padding: 8px 12px;
            border: 1px solid #ccc;
        }
        th {
            background-color: #f4f4f4;
        }
        footer{
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
        }
    </style>
</head>
<body>
    <h1 class="text-center text-dark mb-2" style="font-family:'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif; font-style: italic;">Product List</h1>
    <div class="px-5">
        <form action="{% url 'crm:product' %}" method="get" class="modal-content modal-body border-0 px-5 ">
            <div class="input-group mb-2">
                <input type="text" class="form-control" id="inputModalSearch" name="q" placeholder="Search [name , price , id , category ,all(to get all of them)] ...">
                <button type="submit" class="input-group-text bg-success text-light">
                    <i class="fa fa-fw fa-search text-white"></i>
                </button>
            </div>
        </form>
    </div>
    {% if products %}
    <table class="table table-striped table-hover">
        <thead class="text-light bg-dark">
            <tr>
                <th>ID</th>
                <th>Product Name</th>
                <th>Price</th>
                <th>Category</th>
                <th>Season</th>
                <th>Added by</th>
                <th> Quantity </th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
            <tr>
                <td> <a href="{% url 'crm:product-details' product.id %}" class="text-decoration-none text text-dark"> {{product.id}} </a> </td>
                <td>{{ product.name}}</td>
                <td> {{product.price}} </td>
                <td> {{product.category}} </td>
                <td> {{product.season}} </td>
                <td> {{product.added_by}} </td>
                <td> {{product.quantity}} </td>
            </tr>
            {% endfor %}
            {% else %}
            <h1> No Products in the Database </h1>
            {% endif %}
        </tbody>
    </table>
</body>
</html>

{% endblock content %}

crm/templates/pages/userModel.html
{% extends 'pages/crmbase.html' %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>order List</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            padding: 8px 12px;
            border: 1px solid #ccc;
        }
        th {
            background-color: #f4f4f4;
        }
        footer{
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
        }
    </style>
</head>
<body>
    <h1 class="text-center text-dark mb-2" style="font-family:'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif; font-style: italic;">Users List</h1>
    <div class="px-5">
        <form action="{% url 'crm:user' %}" method="get" class="modal-content modal-body border-0 px-5 ">
            <div class="input-group mb-2">
                <input type="text" class="form-control" id="inputModalSearch" name="q" placeholder="Search [name , price , id , category ,all(to get all of them)] ...">
                <button type="submit" class="input-group-text bg-success text-light">
                    <i class="fa fa-fw fa-search text-white"></i>
                </button>
            </div>
        </form>
    {% if users %}
    <table class="table table-striped table-hover">
        <thead class="text-light bg-dark">
            <tr>
                {% comment %} <th>ID</th> {% endcomment %}
                <th>Username</th>
                <th>Email</th>
                <th>Phone</th>
                <th>nationality</th>
                <th> city </th>
                <th> address </th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td> {{user.user.username}} </td>
                <td> {{user.email}} </td>
                <td> {{user.phone}} </td>
                <td> {{user.nationality}} </td>
                <td> {{user.city}}  </td>
                <td> {{user.address}} </td>
            </tr>
            {% endfor %}
            {% else %}
            <h1> No Orders </h1>
            {% endif %}
        </tbody>
    </table>
</body>
</html>

{% endblock content %}